import { NextAuthProvider } from "./Providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" style={{ backgroundColor: "#f3f3f3" }}>
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="">
            <Navbar />
            <main className="grid">{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
